f=open('Idontexist') # FileIO error